### ISSUE TITLE
access has been blocked by CORS policy error

### ISSUE THREAD

**Issue by ereday** [veritable-tech/text-annotation-react-frontend#1]
Hi, thanks for the blog post at [medium](https://blog.ceshine.net/post/text-annotation-2/). I was trying to use it. For that, I downloaded the this repository as well as the one for [backend](https://github.com/veritable-tech/text-annotation-api-server). As far as I understood, the backend works without any problem. However, when I tried to use it together with the frontent, I got the following error on the chrome console:

> Access to fetch at 'http://localhost:8666/batch/' from origin 'http://localhost:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'

Do you know what could be the problem?

I started the backend by running the `python server.py` command in the corresponding github repository. For the frontend, first, I've downloaded all the packages you mentioned in the blog post via npm, then I went into the text-annotation-react-frontend and run the `npm install` and `npm start` commands. 

The error I in chrome's console is as follows:

```
Access to fetch at 'http://localhost:8666/batch/' from origin 'http://192.168.0.143:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
localhost:8666/batch/:1 Failed to load resource: net::ERR_FAILED
App.js:67 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by ceshine** [comment]
Thanks for the feedback!

Turns out I made a mistake in the [Fetch API calls](https://github.com/veritable-tech/text-annotation-react-frontend/blob/735766076c04918b1f7bd196960fe4501a032631/src/App.js#L18) in the React App. I shouldn't set the `credential` parameter, or should've set it to "same-origin" or "omit". Removing that parameter should fix the problem. The master branch has been updated. Please try it again.

AFAIK, CORS policy is enforced by the browser. My guess is that this aspect of the policy was not strictly enforced in the earlier version of Firefox when I tested it, as I also get the same error in my Firefox now. 

For more information, please refer to [Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials).

**Comment by ereday** [comment]
Thanks!
